name: Retrieve latest teleconnection values

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install the requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Retrieve data with the Python script
        working-directory: teleconnections_data
        run: python retrieve_data.py