name: Retrieve latest teleconnection values

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install the requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Retrieve data with the Python script
        working-directory: teleconnections_data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          chmod +x retrieve_data.py
          python retrieve_data.py
          git add -A
          git commit -m "Latest teleconnection data"
          git push
